
const mobData = [
    { travel: "goo", targetName: "Goo", map: "main" },
    { travel: "bee", targetName: "Bee", map: "main" },
    { travel: "crab", targetName: "Tiny Crab", map: "main" },
    { travel: "minimush", targetName: "Pom Pom", map: "halloween" },
    { travel: "osnake", targetName: "Snake", map: "halloween" },
    { travel: "snake", targetName: "Snake", map: "main" },
    { travel: "rat", targetName: "Rat", map: "main" },
    { travel: "spider", targetName: "Spider", map: "main" },
    { travel: "squig", targetName: "Squig", map: "main" },
    { travel: "squigtoad", targetName: "Squigtoad", map: "main" },
    { travel: "poisio", targetName: "Poisio", map: "main" },
    { travel: "arcticbee", targetName: "Arctic Bee", map: "winterland" },
    { travel: "iceroamer", targetName: "Water Spirit", map: "winterland" },
    { travel: "armadillo", targetName: "Armadillo", map: "main" },
    { travel: "croc", targetName: "Croc", map: "main" },
    { travel: "porcupine", targetName: "Porcupine", map: "desertland" },
    { travel: "scorpion", targetName: "Scorpion", map: "main" },
    { travel: "bigbird", targetName: "Hawk", map: "main" },
    { travel: "stoneworm", targetName: "Stone Worm", map: "spookytown" },
    { travel: "boar", targetName: "Wild Boar", map: "winterland" },
    { travel: "wolf", targetName: "White Wolf", map: "winterland" },
    { travel: "stompy", targetName: "Stompy", map: "winterland" },
    { travel: "crabx", targetName: "Huge Crab", map: "main" },
    { travel: "tortoise", targetName: "Tortoise", map: "main" },
    { travel: "rharpy", targetName: "Rebel Harpy", map: "winterland" },
    { travel: "bat", targetName: "Bat", map: "cave" },
    { travel: "nerfedBat", targetName: "Bat", map: "cave" },
    { travel: "sparkbot", targetName: "Spark Bot", map: "Underground" },
    { travel: "targetNameron", targetName: "targetNameron", map: "Underground" },
    { travel: "mechagnome", targetName: "Mech-a Gnome", map: "cyberland" },
    { travel: "bbpompom", targetName: "Pom Pom", map: "winter_cave", x: -11.49, y: -57.49 },
    { travel: "cgoo", targetName: "Irradiated Goo", map: "arena" },
    { travel: "mole", targetName: "Mole", map: "tunnel" },
    { travel: "pppompom", targetName: "Pom Pom", map: "level2n" },
    { travel: "ent", targetName: "Ent", map: "desertland" },
    { travel: "wolfie", targetName: "Dark Hound", map: "winterland", x: -82, y: -2059 },
    { travel: "gscorpion", targetName: "Scorpion", map: "desertland" },
    { travel: "booboo", targetName: "Boo Boo", map: "spookytown", x: 122.56, y: -679.46 },
    { travel: "ghost", targetName: "Ghost", map: "halloween", x: 491.39, y: -1091 },
    { travel: "dragold", targetName: "Dragold", map: "cave", x: 1115.5, y: -747.5 },
    { travel: "pinkgoo", targetName: "Love Goo", map: parent.S.pinkgoo.map, x: parent.S.pinkgoo.x, y: parent.S.pinkgoo.y },
    { travel: "wabbit", targetName: "Wabbit", map: "idk", },
];
